# This attempts to delete the FlexReports created in the last run of create-flexreports.py.  
# File "previous-run.list" is generated by the create script.  This script reads that file and executes deletion commands.

import requests

# Prompt the user for the API key
api_key = input("Enter your CloudHealth API key: ")

graphql_endpoint = 'https://apps.cloudhealthtech.com/graphql'

# Function to retrieve the access token
def get_access_token(api_key):
    graphql_query = """
    mutation GetAccessToken($apiKey: String!) {
      loginAPI(apiKey: $apiKey) {
        accessToken
      }
    }
    """
    headers = {
        "Content-Type": "application/json"
    }
    access_token_response = requests.post(
        graphql_endpoint,
        json={"query": graphql_query, "variables": {"apiKey": api_key}},
        headers=headers
    )
    if access_token_response.status_code == 200:
        access_token_result = access_token_response.json()
        access_token = access_token_result["data"]["loginAPI"]["accessToken"]
        return access_token
    else:
        print("Failed to retrieve access token. Status code:", access_token_response.status_code)
        print("Response:", access_token_response.text)
        return None

# Function to read FlexReport IDs from the file
def read_report_ids():
    with open("previous-run.list", "r") as id_file:
        return id_file.read().splitlines()

# Read FlexReport IDs from the file
report_ids = read_report_ids()

# Get the access token
access_token = get_access_token(api_key)

# Check if access token is retrieved successfully
if access_token:
    # GraphQL query to delete FlexReports
    delete_report_query = """
    mutation DeleteFlexReport($id: ID!) {
      delete(id: $id)
    }
    """

    # Set the headers for the GraphQL requests
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {access_token}"
    }

    # Iterate through each FlexReport ID and delete the corresponding FlexReport
    for report_id in report_ids:
        delete_variables = {
            "id": report_id
        }

        # Make the GraphQL API call to delete the FlexReport
        delete_response = requests.post(
            graphql_endpoint,
            json={"query": delete_report_query, "variables": delete_variables},
            headers=headers
        )

        if delete_response.status_code == 200:
            #print(f"FlexReport '{report_id}' deleted successfully!")
            print({report_id}, " -- ", {delete_response.text})
        else:
            print(f"Failed to delete FlexReport '{report_id}'. Status code:", delete_response.status_code)
            print("Response:", delete_response.text)
